"""Session persistence: one directory per call under data/sessions/.

  <dir>/audio.wav         8 kHz mono 16-bit recording
  <dir>/session.json      meta + per-engine segments/events/scores + peaks
  <dir>/annotations.json  ground-truth regions (separate: re-annotating
                          never touches results)
"""

from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path


class SessionStore:
    def __init__(self, data_dir: Path):
        self.data_dir = data_dir
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def new_session_dir(self, call_id: str) -> tuple[str, Path]:
        stamp = time.strftime("%Y-%m-%dT%H-%M-%S")
        digest = hashlib.sha256(call_id.encode()).hexdigest()[:8]
        session_id = f"{stamp}_{digest}"
        path = self.data_dir / session_id
        path.mkdir(parents=True, exist_ok=False)
        return session_id, path

    def write_session(self, session_id: str, payload: dict) -> None:
        (self.data_dir / session_id / "session.json").write_text(json.dumps(payload))

    def read_session(self, session_id: str) -> dict:
        return json.loads((self._session_dir(session_id) / "session.json").read_text())

    def audio_path(self, session_id: str) -> Path:
        return self._session_dir(session_id) / "audio.wav"

    def read_annotations(self, session_id: str) -> dict:
        path = self._session_dir(session_id) / "annotations.json"
        if not path.exists():
            return {"speech_regions": []}
        return json.loads(path.read_text())

    def write_annotations(self, session_id: str, payload: dict) -> None:
        (self._session_dir(session_id) / "annotations.json").write_text(json.dumps(payload))

    def list_sessions(self) -> list[dict]:
        out = []
        for path in sorted(self.data_dir.iterdir(), reverse=True):
            meta_path = path / "session.json"
            if not meta_path.exists():
                continue
            try:
                meta = json.loads(meta_path.read_text())
            except (OSError, json.JSONDecodeError):
                continue
            out.append(
                {
                    "id": meta.get("id", path.name),
                    "started_at": meta.get("started_at"),
                    "duration_ms": meta.get("duration_ms"),
                    "engines": sorted((meta.get("engines") or {}).keys()),
                    "annotated": (path / "annotations.json").exists(),
                }
            )
        return out

    def _session_dir(self, session_id: str) -> Path:
        # session ids are generated by us; refuse anything path-like
        if "/" in session_id or "\\" in session_id or ".." in session_id:
            raise ValueError(f"bad session id: {session_id!r}")
        path = self.data_dir / session_id
        if not path.is_dir():
            raise KeyError(session_id)
        return path
